import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

export async function sendInvoiceEmail(to, pdfBuffer, invoiceNumber, details = {}) {
  const {
    tenantName = 'Valued Tenant',
    month = '',
    totalAmount = 0,
    totalPaid = 0,
    remainingBalance = 0,
    status = 'Pending'
  } = details;

  const formattedTotal = Number(totalAmount || 0).toLocaleString('en-IN');
  const formattedPaid = Number(totalPaid || 0).toLocaleString('en-IN');
  const formattedBalance = Number(remainingBalance || 0).toLocaleString('en-IN');

  const htmlContent = `
  <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; background-color: #ffffff;">
    <div style="background: linear-gradient(135deg, #2563eb 0%, #4338ca 100%); padding: 32px 24px; color: #ffffff;">
      <h1 style="margin: 0; font-size: 22px; font-weight: 800; letter-spacing: -0.5px;">PROPERTYBILLS</h1>
      <p style="margin: 4px 0 0; font-size: 13px; color: #e0e7ff;">Property Management Rental Invoice</p>
    </div>

    <div style="padding: 24px; color: #1e293b;">
      <p style="font-size: 15px; margin: 0 0 16px;">Dear <strong>${tenantName}</strong>,</p>
      <p style="font-size: 14px; color: #475569; margin: 0 0 20px; line-height: 1.5;">
        Please find attached your rental invoice <strong>#${invoiceNumber}</strong> for the billing month of <strong>${month || 'N/A'}</strong>.
      </p>

      <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
        <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
          <tr>
            <td style="padding: 6px 0; color: #64748b;">Invoice Number:</td>
            <td style="padding: 6px 0; font-weight: 700; text-align: right; color: #0f172a;">#${invoiceNumber}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748b;">Billing Month:</td>
            <td style="padding: 6px 0; font-weight: 700; text-align: right; color: #0f172a;">${month || 'N/A'}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748b;">Status:</td>
            <td style="padding: 6px 0; font-weight: 700; text-align: right; color: ${status === 'Paid' ? '#10b981' : '#2563eb'};">${status}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748b;">Total Invoice Amount:</td>
            <td style="padding: 6px 0; font-weight: 800; text-align: right; color: #1e293b; font-size: 15px;">Rs. ${formattedTotal}</td>
          </tr>
          <tr>
            <td style="padding: 6px 0; color: #64748b;">Amount Paid So Far:</td>
            <td style="padding: 6px 0; font-weight: 800; text-align: right; color: #10b981; font-size: 15px;">Rs. ${formattedPaid}</td>
          </tr>
          <tr style="border-top: 1px solid #cbd5e1;">
            <td style="padding: 10px 0 4px; font-weight: 700; color: #0f172a;">Remaining Balance:</td>
            <td style="padding: 10px 0 4px; font-weight: 900; text-align: right; color: ${remainingBalance > 0 ? '#d97706' : '#10b981'}; font-size: 17px;">Rs. ${formattedBalance}</td>
          </tr>
        </table>
      </div>

      <p style="font-size: 13px; color: #64748b; margin: 0;">
        The itemized breakdown is available in the attached PDF file (<strong>${invoiceNumber}.pdf</strong>).
      </p>
    </div>

    <div style="background-color: #f1f5f9; padding: 16px 24px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0;">
      Electronically generated by PropertyBills Management System. Thank you!
    </div>
  </div>
  `;

  await transporter.sendMail({
    from: process.env.EMAIL_USER,
    to,
    subject: `Rental Invoice #${invoiceNumber} - ${month || 'Statement'}`,
    text: `Dear ${tenantName},\n\nYour invoice #${invoiceNumber} for ${month} is attached.\nTotal Amount: Rs. ${formattedTotal}\nAmount Paid: Rs. ${formattedPaid}\nRemaining Balance: Rs. ${formattedBalance}\n\nThank you!`,
    html: htmlContent,
    attachments: [{ filename: `${invoiceNumber}.pdf`, content: pdfBuffer }]
  });
}
